### ISSUE TITLE
I want to verify my contract, but the terminal prompts me that I have two suitable contracts, what should I do

### ISSUE THREAD

**Issue by wangyangv1** [PatrickAlphaC/hardhat-erc20-fcc#13]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/49341812/191197841-e6f12407-2926-4fda-9ea0-0b5229c4aae8.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/49341812/191198063-f5c0f84d-6d4d-44f5-adc3-56bc9d7964c3.png">
I want to verify my contract, but the terminal prompts me that I have two suitable contracts, what should I do

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
